### ISSUE TITLE
Plants have become ethereal beings :O

### ISSUE THREAD

**Issue by PixelEyeStudios** [TheRayKid101/Prehistoric-Dinosaur-Biomes#4]
![image](https://user-images.githubusercontent.com/40326233/106631206-70528500-6574-11eb-8d04-5141b6b7c8c1.png)

I praised to the wrong god and he made is wrath clear and now plants have become void
(I just placed them down to grow them)

**Comment by TheRayKid101** [comment]
Resolved the issue with the rendering of the saplings.
