### ISSUE TITLE
Server problem: caused because server does not support frame

### ISSUE THREAD

**Issue by PanJohnny** [TheRayKid101/Prehistoric-Dinosaur-Biomes#5]
This is log.
https://mcpaste.io/8dc9a8c89ef0bb0e
I talked with people on official discord server.
It is caused because your mod didn't support only server thing.

This is the problematic class. It is not supported within server. Please fix this.
`Class names

Official     » dot
Intermediary » net/minecraft/class_437
Yarn         » net/minecraft/client/gui/screen/Screen

Access widener

accessible	class	net/minecraft/client/gui/screen/Screen`

**Comment by TheRayKid101** [comment]
0.1.4 resolves the issue with the server crashing upon load!
