### ISSUE TITLE
Server Crash Upon Loading

### ISSUE THREAD

**Issue by ByteGuy-YT** [TheRayKid101/Prehistoric-Dinosaur-Biomes#7]
When starting my server the server will crash - here is the log - hope this helps :D
[latest.log](https://github.com/TheRayKid101/Prehistoric-Dinosaur-Biomes/files/6030590/latest.log)
If you want it on patebin: https://pastebin.com/U9eG3tK6

**Comment by TheRayKid101** [comment]
0.1.4 resolves the bugs with the server crashing upon load.
